/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlapLike } from "./FlapLike";
export type { FlopLike } from "./FlopLike";
export type { VatLike } from "./VatLike";
export type { Vow } from "./Vow";
