/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  CeRouterLike,
  CeRouterLikeInterface,
} from "../../../contracts/DAOInteraction.sol/CeRouterLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "urn",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "liquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class CeRouterLike__factory {
  static readonly abi = _abi;
  static createInterface(): CeRouterLikeInterface {
    return new utils.Interface(_abi) as CeRouterLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CeRouterLike {
    return new Contract(address, _abi, signerOrProvider) as CeRouterLike;
  }
}
