/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  GemJoinLike,
  GemJoinLikeInterface,
} from "../../../contracts/DAOInteraction.sol/GemJoinLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gem",
    outputs: [
      {
        internalType: "contract IERC20Upgradeable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class GemJoinLike__factory {
  static readonly abi = _abi;
  static createInterface(): GemJoinLikeInterface {
    return new utils.Interface(_abi) as GemJoinLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GemJoinLike {
    return new Contract(address, _abi, signerOrProvider) as GemJoinLike;
  }
}
