/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SpotLike,
  SpotLikeInterface,
} from "../../../contracts/DAOInteraction.sol/SpotLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "ilks",
    outputs: [
      {
        internalType: "contract PipLike",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class SpotLike__factory {
  static readonly abi = _abi;
  static createInterface(): SpotLikeInterface {
    return new utils.Interface(_abi) as SpotLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SpotLike {
    return new Contract(address, _abi, signerOrProvider) as SpotLike;
  }
}
