/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UsbGemLike,
  UsbGemLikeInterface,
} from "../../../contracts/DAOInteraction.sol/UsbGemLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "exit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "join",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class UsbGemLike__factory {
  static readonly abi = _abi;
  static createInterface(): UsbGemLikeInterface {
    return new utils.Interface(_abi) as UsbGemLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UsbGemLike {
    return new Contract(address, _abi, signerOrProvider) as UsbGemLike;
  }
}
