/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ClipperLike,
  ClipperLikeInterface,
} from "../../../../contracts/makerdaoCore/dog.sol/ClipperLike";

const _abi = [
  {
    inputs: [],
    name: "ilk",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tab",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lot",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
      {
        internalType: "address",
        name: "kpr",
        type: "address",
      },
    ],
    name: "kick",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ClipperLike__factory {
  static readonly abi = _abi;
  static createInterface(): ClipperLikeInterface {
    return new utils.Interface(_abi) as ClipperLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ClipperLike {
    return new Contract(address, _abi, signerOrProvider) as ClipperLike;
  }
}
