/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DssCdpManager } from "./DssCdpManager";
export type { UrnHandler } from "./UrnHandler";
export type { VatLike } from "./VatLike";
