/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as abaciSol from "./abaci.sol";
export * as clipSol from "./clip.sol";
export * as dogSol from "./dog.sol";
export * as flapSol from "./flap.sol";
export * as flopSol from "./flop.sol";
export * as joinSol from "./join.sol";
export * as jugSol from "./jug.sol";
export * as potSol from "./pot.sol";
export * as spotSol from "./spot.sol";
export * as usbSol from "./usb.sol";
export * as vatSol from "./vat.sol";
export * as vowSol from "./vow.sol";
