/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VowLike,
  VowLikeInterface,
} from "../../../../contracts/makerdaoCore/flop.sol/VowLike";

const _abi = [
  {
    inputs: [],
    name: "Ash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "kiss",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VowLike__factory {
  static readonly abi = _abi;
  static createInterface(): VowLikeInterface {
    return new utils.Interface(_abi) as VowLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VowLike {
    return new Contract(address, _abi, signerOrProvider) as VowLike;
  }
}
