/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abaciSol from "./abaci.sol";
export type { abaciSol };
import type * as clipSol from "./clip.sol";
export type { clipSol };
import type * as dogSol from "./dog.sol";
export type { dogSol };
import type * as flapSol from "./flap.sol";
export type { flapSol };
import type * as flopSol from "./flop.sol";
export type { flopSol };
import type * as joinSol from "./join.sol";
export type { joinSol };
import type * as jugSol from "./jug.sol";
export type { jugSol };
import type * as potSol from "./pot.sol";
export type { potSol };
import type * as spotSol from "./spot.sol";
export type { spotSol };
import type * as usbSol from "./usb.sol";
export type { usbSol };
import type * as vatSol from "./vat.sol";
export type { vatSol };
import type * as vowSol from "./vow.sol";
export type { vowSol };
